"""Export a trained BitNet checkpoint to a C source file (src/weights.c) and
matching header (src/weights.h) that the on-device inference engine can include.

The Python loader in modelling/bitnet_quant_inference.py is the spec — every
tensor goes through the same round/clamp/dtype path here, then gets serialised
as a packed C array (ternary 2-bit packed; int8/int16 raw little-endian).

Usage:
    python modelling/export_weights.py [path/to/checkpoint.pt]
    # writes src/weights.c and src/weights.h
"""
from __future__ import annotations

from pathlib import Path
import sys
import textwrap

import numpy as np
import torch

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "tests"))

from modelling.bitnet_quant_inference import load_checkpoint, _get  # noqa: E402
from c_harness import pack_ternary, pack_int4  # noqa: E402


# --------------------------------------------------------------------------- #
# Helpers for emitting C array literals
# --------------------------------------------------------------------------- #


def _wrap_bytes(name: str, dtype: str, values: list[int], width: int = 12) -> str:
    """Emit `static const dtype name[N] = { v0, v1, ... };` with line wrapping."""
    body = ",\n".join(
        "    " + ", ".join(f"{v}" for v in values[i : i + width])
        for i in range(0, len(values), width)
    )
    return f"static {dtype} {name}[{len(values)}] = {{\n{body}\n}};\n"


def _pad_to_multiple(W: np.ndarray, multiple: int) -> np.ndarray:
    """Right-pad each row of W (2-D int8) with zeros so width is a multiple of `multiple`.
    The padded values are zero in both the int4 and ternary alphabets, so they
    contribute nothing to the matmul on either side."""
    H, W_ = W.shape
    if W_ % multiple == 0:
        return W
    new_W = ((W_ + multiple - 1) // multiple) * multiple
    out = np.zeros((H, new_W), dtype=W.dtype)
    out[:, :W_] = W
    return out


def _packed_ternary_array(name: str, W: np.ndarray) -> str:
    """Pack a ternary matrix and emit it as `static const char name[N]`.
    If W's width is not a multiple of 4 we right-pad with zeros — those positions
    don't change the dot product (zero × anything = 0) and the C inner-loop reads
    them as ternary 0b00 = no contribution."""
    packed = pack_ternary(_pad_to_multiple(W, 4))
    values = list(packed)  # bytes → ints
    return _wrap_bytes(name, "char", values, width=12)


def _packed_int4_array(name: str, W: np.ndarray) -> str:
    """Pack an int4 matrix and emit it as `static const char name[N]`.
    If W's width is odd, the high nibble of the last byte in each row is zero."""
    packed = pack_int4(_pad_to_multiple(W, 2))
    values = list(packed)
    return _wrap_bytes(name, "char", values, width=12)


def _int8_array(name: str, arr: np.ndarray) -> str:
    return _wrap_bytes(name, "signed char", [int(x) for x in arr.flatten()], width=12)


def _int16_array(name: str, arr: np.ndarray) -> str:
    return _wrap_bytes(name, "signed int", [int(x) for x in arr.flatten()], width=8)


# --------------------------------------------------------------------------- #
# Main exporter
# --------------------------------------------------------------------------- #


def export(ckpt_path: Path, out_c: Path, out_h: Path) -> None:
    weights, vocab = load_checkpoint(ckpt_path)
    cfg = weights.cfg
    if cfg.n_layer != 3:
        raise NotImplementedError("exporter currently hardcoded for n_layer=3")

    vocab_size = cfg.vocab_size
    n_embd = cfg.n_embd
    state_size = cfg.state_size
    conv_kernel = cfg.conv_kernel
    block_size = cfg.block_size

    # The C inner loops on ternary_linear / int4_logits round the inner-product
    # length up to a multiple of 4 (resp. 2) and read x past the logical width.
    # We pad the activation buffers so those reads land on zero bytes.
    n_embd_padded = ((n_embd + 3) // 4) * 4
    n_hidden_padded = ((2 * n_embd + 3) // 4) * 4

    # Per-tensor type used for conv / SSM C / head: ternary_matrix vs int4_matrix.
    conv_struct = "int4_matrix" if weights.int4_conv else "ternary_matrix"
    Cmat_struct = "int4_matrix" if weights.int4_ssm_C else "ternary_matrix"
    head_struct = "int4_matrix" if weights.int4_head else "ternary_matrix"

    # ------------------------------------------------------------------ Header
    header = textwrap.dedent(f"""\
        /* AUTO-GENERATED by modelling/export_weights.py — do not edit by hand. */
        #ifndef WEIGHTS_H
        #define WEIGHTS_H

        #include "matrix.h"

        #define VOCAB_SIZE     {vocab_size}
        #define N_EMBD         {n_embd}
        #define N_EMBD_PADDED  {n_embd_padded}      /* round up to a multiple of 4 */
        #define N_HIDDEN       {2 * n_embd}     /* in_proj output (gated) */
        #define N_HIDDEN_PADDED {n_hidden_padded}
        #define N_LAYER        {cfg.n_layer}
        #define STATE_SIZE     {state_size}
        #define CONV_KERNEL    {conv_kernel}
        #define BLOCK_SIZE     {block_size}

        /* Vocab table for converting token ids back to characters. */
        extern const char itos[VOCAB_SIZE];

        /* Token embedding table. */
        extern struct char_matrix token_embedding;

        /* Per-block weights and per-block mutable state. Indexed 0..2. */
        struct block_weights {{
            struct ternary_matrix *in_proj_W;
            struct int_matrix     *in_proj_bias;
            unsigned char          in_proj_shift;
            struct {conv_struct}    *conv_W;
            unsigned char          conv_shift;
            struct char_matrix    *decay;
            struct ternary_matrix *B;
            struct {Cmat_struct}    *C_mat;
            struct char_matrix    *D;
            unsigned char          ssm_out_shift;
            unsigned char          d_shift;
            unsigned char          gate_shift;
            struct ternary_matrix *out_proj_W;
            struct int_matrix     *out_proj_bias;
            unsigned char          out_proj_shift;
        }};

        struct block_state {{
            struct char_matrix    *ssm_state;     /* (N_EMBD, STATE_SIZE) */
            struct char_matrix    *conv_window;   /* (CONV_KERNEL, N_EMBD) */
        }};

        extern struct block_weights blocks[N_LAYER];
        extern struct block_state   block_states[N_LAYER];

        /* Head: int4 weight, no bias, learned shift; emits int16 logits. */
        extern struct {head_struct} head_W;
        extern const unsigned char head_shift;

        /* Scratch buffers shared across the inference path. Buffers that feed
         * into ternary_linear / int4_logits are over-allocated to N_EMBD_PADDED
         * so the inner loops can safely read past the logical width onto zeros. */
        extern struct char_matrix x_buf;          /* (N_EMBD, 1)  residual stream */
        extern struct char_matrix proj_buf;       /* (N_HIDDEN, 1) in_proj output */
        extern struct char_matrix u_buf;          /* (N_EMBD, 1)  pre-conv u */
        extern struct char_matrix gate_buf;       /* (N_EMBD, 1)  gate */
        extern struct char_matrix u_post_conv;    /* (N_EMBD, 1)  post-conv u */
        extern struct char_matrix y_buf;          /* (N_EMBD, 1)  ssm output */
        extern struct char_matrix y_gated;        /* (N_EMBD, 1)  post-gate */
        extern struct char_matrix y_outproj;      /* (N_EMBD, 1)  post out_proj */
        extern struct int_matrix  tmp_int;        /* (N_HIDDEN, 1) ternary_linear scratch */
        extern struct int_matrix  logits;         /* (VOCAB_SIZE, 1) */

        #endif
        """)
    out_h.write_text(header)

    # ---------------------------------------------------------------- C source
    parts: list[str] = []
    parts.append('#include "weights.h"\n\n')

    # Vocab itos (lowercase letters + space)
    itos = _get(vocab, "itos")
    chars = ["'" + (c if c != "'" else "\\'") + "'" for c in itos]
    parts.append(f"const char itos[VOCAB_SIZE] = {{ {', '.join(chars)} }};\n\n")

    # Token embedding
    te = weights.token_embedding.numpy()
    parts.append(_int8_array("token_embedding_data", te))
    parts.append(
        f"struct char_matrix token_embedding = {{ "
        f"(signed char *)token_embedding_data, {te.shape[0]}, {te.shape[1]} }};\n\n"
    )

    # Per-block weights (data + struct + per-block mutable state buffers)
    for i, bw in enumerate(weights.blocks):
        parts.append(f"/* ---------------- Block {i} ---------------- */\n")
        # in_proj — ternary, in_f may not be a multiple of 4 (we pad on disk)
        parts.append(_packed_ternary_array(f"in_proj_W_{i}_data", bw.in_proj_weight.numpy()))
        parts.append(
            f"static struct ternary_matrix in_proj_W_{i} = {{ "
            f"in_proj_W_{i}_data, {bw.in_proj_weight.shape[0]}, {bw.in_proj_weight.shape[1]} }};\n"
        )
        parts.append(_int16_array(f"in_proj_bias_{i}_data", bw.in_proj_bias.numpy()))
        parts.append(
            f"static struct int_matrix in_proj_bias_{i} = {{ "
            f"(signed int *)in_proj_bias_{i}_data, {bw.in_proj_bias.shape[0]}, 1 }};\n\n"
        )
        # conv — int4 in the deployable model; pack appropriately
        if weights.int4_conv:
            parts.append(_packed_int4_array(f"conv_W_{i}_data", bw.conv_weight.numpy()))
            parts.append(
                f"static struct int4_matrix conv_W_{i} = {{ "
                f"conv_W_{i}_data, {bw.conv_weight.shape[0]}, {bw.conv_weight.shape[1]} }};\n\n"
            )
        else:
            parts.append(_packed_ternary_array(f"conv_W_{i}_data", bw.conv_weight.numpy()))
            parts.append(
                f"static struct ternary_matrix conv_W_{i} = {{ "
                f"conv_W_{i}_data, {bw.conv_weight.shape[0]}, {bw.conv_weight.shape[1]} }};\n\n"
            )
        # decay, B, C_mat, D
        parts.append(_int8_array(f"decay_{i}_data", bw.decay.numpy()))
        parts.append(
            f"static struct char_matrix decay_{i} = {{ "
            f"(signed char *)decay_{i}_data, {bw.decay.shape[0]}, {bw.decay.shape[1]} }};\n"
        )
        parts.append(_packed_ternary_array(f"B_{i}_data", bw.B.numpy()))
        parts.append(
            f"static struct ternary_matrix B_{i} = {{ "
            f"B_{i}_data, {bw.B.shape[0]}, {bw.B.shape[1]} }};\n"
        )
        if weights.int4_ssm_C:
            parts.append(_packed_int4_array(f"C_mat_{i}_data", bw.C_mat.numpy()))
            parts.append(
                f"static struct int4_matrix C_mat_{i} = {{ "
                f"C_mat_{i}_data, {bw.C_mat.shape[0]}, {bw.C_mat.shape[1]} }};\n"
            )
        else:
            parts.append(_packed_ternary_array(f"C_mat_{i}_data", bw.C_mat.numpy()))
            parts.append(
                f"static struct ternary_matrix C_mat_{i} = {{ "
                f"C_mat_{i}_data, {bw.C_mat.shape[0]}, {bw.C_mat.shape[1]} }};\n"
            )
        parts.append(_int8_array(f"D_{i}_data", bw.D.numpy()))
        parts.append(
            f"static struct char_matrix D_{i} = {{ "
            f"(signed char *)D_{i}_data, 1, {bw.D.shape[0]} }};\n\n"
        )
        # out_proj — ternary, in_f may not be a multiple of 4
        parts.append(_packed_ternary_array(f"out_proj_W_{i}_data", bw.out_proj_weight.numpy()))
        parts.append(
            f"static struct ternary_matrix out_proj_W_{i} = {{ "
            f"out_proj_W_{i}_data, {bw.out_proj_weight.shape[0]}, {bw.out_proj_weight.shape[1]} }};\n"
        )
        parts.append(_int16_array(f"out_proj_bias_{i}_data", bw.out_proj_bias.numpy()))
        parts.append(
            f"static struct int_matrix out_proj_bias_{i} = {{ "
            f"(signed int *)out_proj_bias_{i}_data, {bw.out_proj_bias.shape[0]}, 1 }};\n\n"
        )
        # mutable per-block state buffers (BSS, zero-initialised at start)
        parts.append(
            f"static signed char ssm_state_{i}_data[N_EMBD * STATE_SIZE];\n"
            f"static struct char_matrix ssm_state_{i} = {{ ssm_state_{i}_data, N_EMBD, STATE_SIZE }};\n"
            f"static signed char conv_window_{i}_data[CONV_KERNEL * N_EMBD];\n"
            f"static struct char_matrix conv_window_{i} = {{ conv_window_{i}_data, CONV_KERNEL, N_EMBD }};\n\n"
        )

    # blocks[] aggregate
    parts.append("struct block_weights blocks[N_LAYER] = {\n")
    for i, bw in enumerate(weights.blocks):
        parts.append(
            f"    {{ &in_proj_W_{i}, &in_proj_bias_{i}, {bw.in_proj_shift},\n"
            f"      &conv_W_{i}, {bw.conv_shift},\n"
            f"      &decay_{i}, &B_{i}, &C_mat_{i}, &D_{i},\n"
            f"      {bw.ssm_out_shift}, {bw.d_shift}, {bw.gate_shift},\n"
            f"      &out_proj_W_{i}, &out_proj_bias_{i}, {bw.out_proj_shift} }},\n"
        )
    parts.append("};\n\n")

    parts.append("struct block_state block_states[N_LAYER] = {\n")
    for i in range(cfg.n_layer):
        parts.append(f"    {{ &ssm_state_{i}, &conv_window_{i} }},\n")
    parts.append("};\n\n")

    # Head — int4 in the deployable model
    if weights.int4_head:
        parts.append(_packed_int4_array("head_W_data", weights.head_weight.numpy()))
        parts.append(
            f"struct int4_matrix head_W = {{ "
            f"head_W_data, {weights.head_weight.shape[0]}, {weights.head_weight.shape[1]} }};\n"
        )
    else:
        parts.append(_packed_ternary_array("head_W_data", weights.head_weight.numpy()))
        parts.append(
            f"struct ternary_matrix head_W = {{ "
            f"head_W_data, {weights.head_weight.shape[0]}, {weights.head_weight.shape[1]} }};\n"
        )
    parts.append(f"const unsigned char head_shift = {weights.head_shift};\n\n")

    # Scratch buffers (BSS). Single-token activations are stored as (C, 1)
    # column vectors so they can be passed straight into ternary_linear as `x`.
    # x_buf and y_gated feed into ternary_linear / int4_logits whose inner
    # loops read past N_EMBD up to N_EMBD_PADDED — the buffers are sized to
    # N_EMBD_PADDED and zero-initialised so those reads land on zero.
    parts.append(
        "static signed char x_buf_data[N_EMBD_PADDED];\n"
        "struct char_matrix x_buf = { x_buf_data, N_EMBD, 1 };\n"
        "static signed char proj_buf_data[N_HIDDEN];\n"
        "struct char_matrix proj_buf = { proj_buf_data, N_HIDDEN, 1 };\n"
        "static signed char u_buf_data[N_EMBD];\n"
        "struct char_matrix u_buf = { u_buf_data, N_EMBD, 1 };\n"
        "static signed char gate_buf_data[N_EMBD];\n"
        "struct char_matrix gate_buf = { gate_buf_data, N_EMBD, 1 };\n"
        "static signed char u_post_conv_data[N_EMBD];\n"
        "struct char_matrix u_post_conv = { u_post_conv_data, N_EMBD, 1 };\n"
        "static signed char y_buf_data[N_EMBD];\n"
        "struct char_matrix y_buf = { y_buf_data, N_EMBD, 1 };\n"
        "static signed char y_gated_data[N_EMBD_PADDED];\n"
        "struct char_matrix y_gated = { y_gated_data, N_EMBD, 1 };\n"
        "static signed char y_outproj_data[N_EMBD];\n"
        "struct char_matrix y_outproj = { y_outproj_data, N_EMBD, 1 };\n"
        "static signed int  tmp_int_data[N_HIDDEN];\n"
        "struct int_matrix  tmp_int = { tmp_int_data, N_HIDDEN, 1 };\n"
        "static signed int  logits_data[VOCAB_SIZE];\n"
        "struct int_matrix  logits = { logits_data, VOCAB_SIZE, 1 };\n"
    )

    out_c.write_text("".join(parts))


def main() -> None:
    ckpt = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "build" / "bitnet_quant_final_v3.pt"
    out_c = REPO / "src" / "weights.c"
    out_h = REPO / "src" / "weights.h"
    export(ckpt, out_c, out_h)
    print(f"wrote {out_c} ({out_c.stat().st_size:,} bytes)")
    print(f"wrote {out_h}")


if __name__ == "__main__":
    main()
