"""Export a trained BitNet checkpoint to a C source file (src/weights.c) and
matching header (src/weights.h) that the on-device inference engine can include.

The Python loader in modelling/bitnet_quant_inference.py is the spec — every
tensor goes through the same round/clamp/dtype path here, then gets serialised
as a packed C array (ternary 2-bit packed; int8/int16 raw little-endian).

Usage:
    python modelling/export_weights.py [path/to/checkpoint.pt]
    # writes src/weights.c and src/weights.h
"""
from __future__ import annotations

from pathlib import Path
import sys
import textwrap

import numpy as np
import torch

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "tests"))

from modelling.bitnet_quant_inference import load_checkpoint  # noqa: E402
from c_harness import pack_ternary  # noqa: E402


# --------------------------------------------------------------------------- #
# Helpers for emitting C array literals
# --------------------------------------------------------------------------- #


def _wrap_bytes(name: str, dtype: str, values: list[int], width: int = 12) -> str:
    """Emit `static const dtype name[N] = { v0, v1, ... };` with line wrapping."""
    body = ",\n".join(
        "    " + ", ".join(f"{v}" for v in values[i : i + width])
        for i in range(0, len(values), width)
    )
    return f"static {dtype} {name}[{len(values)}] = {{\n{body}\n}};\n"


def _packed_ternary_array(name: str, W: np.ndarray) -> str:
    """Pack a ternary matrix and emit it as `static const char name[N]`."""
    packed = pack_ternary(W)
    values = list(packed)  # bytes → ints
    return _wrap_bytes(name, "char", values, width=12)


def _int8_array(name: str, arr: np.ndarray) -> str:
    return _wrap_bytes(name, "signed char", [int(x) for x in arr.flatten()], width=12)


def _int16_array(name: str, arr: np.ndarray) -> str:
    return _wrap_bytes(name, "signed int", [int(x) for x in arr.flatten()], width=8)


# --------------------------------------------------------------------------- #
# Main exporter
# --------------------------------------------------------------------------- #


def export(ckpt_path: Path, out_c: Path, out_h: Path) -> None:
    weights, vocab = load_checkpoint(ckpt_path)
    cfg = weights.cfg
    if cfg.n_layer != 3:
        raise NotImplementedError("exporter currently hardcoded for n_layer=3")

    vocab_size = cfg.vocab_size
    n_embd = cfg.n_embd
    state_size = cfg.state_size
    conv_kernel = cfg.conv_kernel
    block_size = cfg.block_size

    # ------------------------------------------------------------------ Header
    header = textwrap.dedent(f"""\
        /* AUTO-GENERATED by modelling/export_weights.py — do not edit by hand. */
        #ifndef WEIGHTS_H
        #define WEIGHTS_H

        #include "matrix.h"

        #define VOCAB_SIZE  {vocab_size}
        #define N_EMBD      {n_embd}
        #define N_HIDDEN    {2 * n_embd}     /* in_proj output (gated) */
        #define N_LAYER     {cfg.n_layer}
        #define STATE_SIZE  {state_size}
        #define CONV_KERNEL {conv_kernel}
        #define BLOCK_SIZE  {block_size}

        /* Vocab table for converting token ids back to characters. */
        extern const char itos[VOCAB_SIZE];

        /* Token embedding table. */
        extern struct char_matrix token_embedding;

        /* Per-block weights and per-block mutable state. Indexed 0..2. */
        struct block_weights {{
            struct ternary_matrix *in_proj_W;
            struct int_matrix     *in_proj_bias;
            unsigned char          in_proj_shift;
            struct ternary_matrix *conv_W;
            unsigned char          conv_shift;
            struct char_matrix    *decay;
            struct ternary_matrix *B;
            struct ternary_matrix *C_mat;
            struct char_matrix    *D;
            unsigned char          ssm_out_shift;
            unsigned char          d_shift;
            unsigned char          gate_shift;
            struct ternary_matrix *out_proj_W;
            struct int_matrix     *out_proj_bias;
            unsigned char          out_proj_shift;
        }};

        struct block_state {{
            struct char_matrix    *ssm_state;     /* (N_EMBD, STATE_SIZE) */
            struct char_matrix    *conv_window;   /* (CONV_KERNEL, N_EMBD) */
        }};

        extern struct block_weights blocks[N_LAYER];
        extern struct block_state   block_states[N_LAYER];

        /* Head: ternary_linear with no bias, learned shift (argmax-invariant). */
        extern struct ternary_matrix head_W;
        extern const unsigned char head_shift;

        /* Scratch buffers shared across the inference path. */
        extern struct char_matrix x_buf;          /* (1, N_EMBD)  residual stream */
        extern struct char_matrix proj_buf;       /* (1, N_HIDDEN) in_proj output */
        extern struct char_matrix u_buf;          /* (1, N_EMBD)  pre-conv u */
        extern struct char_matrix gate_buf;       /* (1, N_EMBD)  gate */
        extern struct char_matrix u_post_conv;    /* (1, N_EMBD)  post-conv u */
        extern struct char_matrix y_buf;          /* (1, N_EMBD)  ssm output */
        extern struct char_matrix y_gated;        /* (1, N_EMBD)  post-gate */
        extern struct char_matrix y_outproj;      /* (1, N_EMBD)  post out_proj */
        extern struct int_matrix  tmp_int;        /* (N_HIDDEN, 1) ternary_linear scratch */
        extern struct int_matrix  logits;         /* (1, VOCAB_SIZE) */

        #endif
        """)
    out_h.write_text(header)

    # ---------------------------------------------------------------- C source
    parts: list[str] = []
    parts.append('#include "weights.h"\n\n')

    # Vocab itos (lowercase letters + space)
    itos = vocab["itos"]
    chars = ["'" + (c if c != "'" else "\\'") + "'" for c in itos]
    parts.append(f"const char itos[VOCAB_SIZE] = {{ {', '.join(chars)} }};\n\n")

    # Token embedding
    te = weights.token_embedding.numpy()
    parts.append(_int8_array("token_embedding_data", te))
    parts.append(
        f"struct char_matrix token_embedding = {{ "
        f"(signed char *)token_embedding_data, {te.shape[0]}, {te.shape[1]} }};\n\n"
    )

    # Per-block weights (data + struct + per-block mutable state buffers)
    for i, bw in enumerate(weights.blocks):
        parts.append(f"/* ---------------- Block {i} ---------------- */\n")
        # in_proj
        parts.append(_packed_ternary_array(f"in_proj_W_{i}_data", bw.in_proj_weight.numpy()))
        parts.append(
            f"static struct ternary_matrix in_proj_W_{i} = {{ "
            f"in_proj_W_{i}_data, {bw.in_proj_weight.shape[0]}, {bw.in_proj_weight.shape[1]} }};\n"
        )
        parts.append(_int16_array(f"in_proj_bias_{i}_data", bw.in_proj_bias.numpy()))
        parts.append(
            f"static struct int_matrix in_proj_bias_{i} = {{ "
            f"(signed int *)in_proj_bias_{i}_data, {bw.in_proj_bias.shape[0]}, 1 }};\n\n"
        )
        # conv
        parts.append(_packed_ternary_array(f"conv_W_{i}_data", bw.conv_weight.numpy()))
        parts.append(
            f"static struct ternary_matrix conv_W_{i} = {{ "
            f"conv_W_{i}_data, {bw.conv_weight.shape[0]}, {bw.conv_weight.shape[1]} }};\n\n"
        )
        # decay, B, C_mat, D
        parts.append(_int8_array(f"decay_{i}_data", bw.decay.numpy()))
        parts.append(
            f"static struct char_matrix decay_{i} = {{ "
            f"(signed char *)decay_{i}_data, {bw.decay.shape[0]}, {bw.decay.shape[1]} }};\n"
        )
        parts.append(_packed_ternary_array(f"B_{i}_data", bw.B.numpy()))
        parts.append(
            f"static struct ternary_matrix B_{i} = {{ "
            f"B_{i}_data, {bw.B.shape[0]}, {bw.B.shape[1]} }};\n"
        )
        parts.append(_packed_ternary_array(f"C_mat_{i}_data", bw.C_mat.numpy()))
        parts.append(
            f"static struct ternary_matrix C_mat_{i} = {{ "
            f"C_mat_{i}_data, {bw.C_mat.shape[0]}, {bw.C_mat.shape[1]} }};\n"
        )
        parts.append(_int8_array(f"D_{i}_data", bw.D.numpy()))
        parts.append(
            f"static struct char_matrix D_{i} = {{ "
            f"(signed char *)D_{i}_data, 1, {bw.D.shape[0]} }};\n\n"
        )
        # out_proj
        parts.append(_packed_ternary_array(f"out_proj_W_{i}_data", bw.out_proj_weight.numpy()))
        parts.append(
            f"static struct ternary_matrix out_proj_W_{i} = {{ "
            f"out_proj_W_{i}_data, {bw.out_proj_weight.shape[0]}, {bw.out_proj_weight.shape[1]} }};\n"
        )
        parts.append(_int16_array(f"out_proj_bias_{i}_data", bw.out_proj_bias.numpy()))
        parts.append(
            f"static struct int_matrix out_proj_bias_{i} = {{ "
            f"(signed int *)out_proj_bias_{i}_data, {bw.out_proj_bias.shape[0]}, 1 }};\n\n"
        )
        # mutable per-block state buffers (BSS, zero-initialised at start)
        parts.append(
            f"static signed char ssm_state_{i}_data[N_EMBD * STATE_SIZE];\n"
            f"static struct char_matrix ssm_state_{i} = {{ ssm_state_{i}_data, N_EMBD, STATE_SIZE }};\n"
            f"static signed char conv_window_{i}_data[CONV_KERNEL * N_EMBD];\n"
            f"static struct char_matrix conv_window_{i} = {{ conv_window_{i}_data, CONV_KERNEL, N_EMBD }};\n\n"
        )

    # blocks[] aggregate
    parts.append("struct block_weights blocks[N_LAYER] = {\n")
    for i, bw in enumerate(weights.blocks):
        parts.append(
            f"    {{ &in_proj_W_{i}, &in_proj_bias_{i}, {bw.in_proj_shift},\n"
            f"      &conv_W_{i}, {bw.conv_shift},\n"
            f"      &decay_{i}, &B_{i}, &C_mat_{i}, &D_{i},\n"
            f"      {bw.ssm_out_shift}, {bw.d_shift}, {bw.gate_shift},\n"
            f"      &out_proj_W_{i}, &out_proj_bias_{i}, {bw.out_proj_shift} }},\n"
        )
    parts.append("};\n\n")

    parts.append("struct block_state block_states[N_LAYER] = {\n")
    for i in range(cfg.n_layer):
        parts.append(f"    {{ &ssm_state_{i}, &conv_window_{i} }},\n")
    parts.append("};\n\n")

    # Head
    parts.append(_packed_ternary_array("head_W_data", weights.head_weight.numpy()))
    parts.append(
        f"struct ternary_matrix head_W = {{ "
        f"head_W_data, {weights.head_weight.shape[0]}, {weights.head_weight.shape[1]} }};\n"
    )
    parts.append(f"const unsigned char head_shift = {weights.head_shift};\n\n")

    # Scratch buffers (BSS). Single-token activations are stored as (C, 1)
    # column vectors so they can be passed straight into ternary_linear as `x`.
    # All "(C, 1)" buffers can also be read as flat C-byte arrays.
    parts.append(
        "static signed char x_buf_data[N_EMBD];\n"
        "struct char_matrix x_buf = { x_buf_data, N_EMBD, 1 };\n"
        "static signed char proj_buf_data[N_HIDDEN];\n"
        "struct char_matrix proj_buf = { proj_buf_data, N_HIDDEN, 1 };\n"
        "static signed char u_buf_data[N_EMBD];\n"
        "struct char_matrix u_buf = { u_buf_data, N_EMBD, 1 };\n"
        "static signed char gate_buf_data[N_EMBD];\n"
        "struct char_matrix gate_buf = { gate_buf_data, N_EMBD, 1 };\n"
        "static signed char u_post_conv_data[N_EMBD];\n"
        "struct char_matrix u_post_conv = { u_post_conv_data, N_EMBD, 1 };\n"
        "static signed char y_buf_data[N_EMBD];\n"
        "struct char_matrix y_buf = { y_buf_data, N_EMBD, 1 };\n"
        "static signed char y_gated_data[N_EMBD];\n"
        "struct char_matrix y_gated = { y_gated_data, N_EMBD, 1 };\n"
        "static signed char y_outproj_data[N_EMBD];\n"
        "struct char_matrix y_outproj = { y_outproj_data, N_EMBD, 1 };\n"
        "static signed int  tmp_int_data[N_HIDDEN];\n"
        "struct int_matrix  tmp_int = { tmp_int_data, N_HIDDEN, 1 };\n"
        "static signed int  logits_data[VOCAB_SIZE];\n"
        "struct int_matrix  logits = { logits_data, VOCAB_SIZE, 1 };\n"
    )

    out_c.write_text("".join(parts))


def main() -> None:
    ckpt = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "build" / "bitnet_quant_npe84.pt"
    out_c = REPO / "src" / "weights.c"
    out_h = REPO / "src" / "weights.h"
    export(ckpt, out_c, out_h)
    print(f"wrote {out_c} ({out_c.stat().st_size:,} bytes)")
    print(f"wrote {out_h}")


if __name__ == "__main__":
    main()
