/* AUTO-GENERATED by modelling/export_weights.py — do not edit by hand. */
#ifndef WEIGHTS_H
#define WEIGHTS_H

#include "matrix.h"

#define VOCAB_SIZE     27
#define N_EMBD         56
#define N_EMBD_PADDED  56      /* round up to a multiple of 4 */
#define N_HIDDEN       112     /* in_proj output (gated) */
#define N_HIDDEN_PADDED 112
#define N_LAYER        3
#define STATE_SIZE     8
#define CONV_KERNEL    4
#define BLOCK_SIZE     64

/* Vocab table for converting token ids back to characters. */
extern const char itos[VOCAB_SIZE];

/* Token embedding table. */
extern struct char_matrix token_embedding;

/* Per-block weights and per-block mutable state. Indexed 0..2. */
struct block_weights {
    struct ternary_matrix *in_proj_W;
    struct int_matrix     *in_proj_bias;
    unsigned char          in_proj_shift;
    struct int4_matrix    *conv_W;
    unsigned char          conv_shift;
    struct char_matrix    *decay;
    struct ternary_matrix *B;
    struct int4_matrix    *C_mat;
    struct char_matrix    *D;
    unsigned char          ssm_out_shift;
    unsigned char          d_shift;
    unsigned char          gate_shift;
    struct ternary_matrix *out_proj_W;
    struct int_matrix     *out_proj_bias;
    unsigned char          out_proj_shift;
};

struct block_state {
    struct char_matrix    *ssm_state;     /* (N_EMBD, STATE_SIZE) */
    struct char_matrix    *conv_window;   /* (CONV_KERNEL, N_EMBD) */
};

extern struct block_weights blocks[N_LAYER];
extern struct block_state   block_states[N_LAYER];

/* Head: int4 weight, no bias, learned shift; emits int16 logits. */
extern struct int4_matrix head_W;
extern const unsigned char head_shift;

/* Softmax-sampling LUT, baked at export time from `make_exp_lut(T)`.
 * `lut[d] = round(255 * exp(-d / T))` for d in [0, EXP_LUT_SIZE). */
#define EXP_LUT_SIZE 16
extern const unsigned char exp_lut[EXP_LUT_SIZE];

/* Scratch buffers shared across the inference path. Buffers that feed
 * into ternary_linear / int4_logits are over-allocated to N_EMBD_PADDED
 * so the inner loops can safely read past the logical width onto zeros. */
extern struct char_matrix x_buf;          /* (N_EMBD, 1)  residual stream */
extern struct char_matrix proj_buf;       /* (N_HIDDEN, 1) in_proj output */
extern struct char_matrix u_buf;          /* (N_EMBD, 1)  pre-conv u */
extern struct char_matrix gate_buf;       /* (N_EMBD, 1)  gate */
extern struct char_matrix u_post_conv;    /* (N_EMBD, 1)  post-conv u */
extern struct char_matrix y_buf;          /* (N_EMBD, 1)  ssm output */
extern struct char_matrix y_gated;        /* (N_EMBD, 1)  post-gate */
extern struct char_matrix y_outproj;      /* (N_EMBD, 1)  post out_proj */
extern struct int_matrix  tmp_int;        /* (N_HIDDEN, 1) ternary_linear scratch */
extern struct int_matrix  logits;         /* (VOCAB_SIZE, 1) */

#endif
